### ISSUE TITLE
compile errog

### ISSUE THREAD

**Issue by autodiag** [cropinghigh/sdrpp-tetra-demodulator#16]
for version 5 month back all ok
i am need compile latest version but get this errors :/

ad@ad-ttp:~/sdrpp-tetra-demodulator/build$ make
[  3%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/hurdle.c.o
[  6%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/taa1.c.o
[  9%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea1.c.o
[ 12%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea2.c.o
[ 16%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea3.c.o
[ 19%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c: In function ‘tetra_crypto_db_init’:
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:112:22: warning: implicit declaration of function ‘talloc_zero_array’ [-Wimplicit-function-declaration]
  112 |         tcdb->keys = talloc_zero_array(NULL, struct tetra_key, TCDB_ALLOC_BLOCK_SIZE);
      |                      ^~~~~~~~~~~~~~~~~
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:112:46: error: expected expression before ‘struct’
  112 |         tcdb->keys = talloc_zero_array(NULL, struct tetra_key, TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:113:46: error: expected expression before ‘struct’
  113 |         tcdb->nets = talloc_zero_array(NULL, struct tetra_netinfo, TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c: In function ‘load_keystore’:
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:324:46: warning: implicit declaration of function ‘talloc_realloc’ [-Wimplicit-function-declaration]
  324 |                                 tcdb->nets = talloc_realloc(NULL, tcdb->nets, struct tetra_netinfo, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~~~~~~~~~
/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:324:79: error: expected expression before ‘struct’
  324 |               tcdb->nets = talloc_realloc(NULL, tcdb->nets, struct tetra_netinfo, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                                             ^~~~~~

/home/ad/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:343:79: error: expected expression before ‘struct’
  343 |               tcdb->keys = talloc_realloc(NULL, tcdb->keys, struct tetra_key, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                                             ^~~~~~

make[2]: *** [CMakeFiles/tetra_demodulator.dir/build.make:146: CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o] Chyba 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/tetra_demodulator.dir/all] Chyba 2
make: *** [Makefile:136: all] Chyba 2

**Comment by cropinghigh** [comment]
Make sure you have libosmocom (and libosmocom-dev if on debian) installed

**Comment by Boris-A777** [comment]
Do you mean libosmocore?libosmocom I can not find one Debian.libosmocore and libosmocore-dev are installed.Am 21.02.2024 18:55 schrieb cropinghigh ***@***.***>:
Make sure you have libosmocom (and libosmocom-dev if on debian) installed

**Comment by autodiag** [comment]
its Ubuntu,Mint distro 21
osmocom have instaled,but anithel pc build ok :/

BTW please add back out data from decoder via UDP

**Comment by autodiag** [comment]
fixed reinstall libosmocore
