### ISSUE TITLE
Another undefined symbol issue

### ISSUE THREAD

**Issue by artur6768** [cropinghigh/sdrpp-tetra-demodulator#18]
Hello everyone!

For some reason when I use the newer versions of tetra demodulator after  [change talloc context to global](https://github.com/cropinghigh/sdrpp-tetra-demodulator/commit/206ab9f60861faa5b145e04ba9610206d23dec26) I get the following error when opening SDR++:
undefined symbol: osmo_ctx
The module itself compiles without issues, but when SDR++ loades, gaves that error. 
I tried to compile osmocore & installing it manually, but the same error happened. 
Currently I'm using Linux Mint 20.3 & latest SDR++ ( commit 867a868 ) 

Thanks, have a nice day.

**Comment by cropinghigh** [comment]
Try updating to the latest commit and latest libosmocore version

**Comment by artur6768** [comment]
Just cloned the latest libosmocore, SDR++, & tetra-demodulator from github, compiled & installed all of them but unfortunately the same error happens.

[24/03/2024 17:27:54.000] [ERROR] Couldn't load /usr/lib/sdrpp/plugins/tetra_demodulator.so: /usr/lib/sdrpp/plugins/tetra_demodulator.so: undefined symbol: osmo_ctx

Compiling & installing the https://github.com/cropinghigh/sdrpp-tetra-demodulator/commit/4510250ff6debe03d2e7e5ee5676e2980f1dfc83 version still works tho

**Comment by artur6768** [comment]
Update:
Issue fixed, I had to install a older libosmocore version, in this case libosmocore-osmith-1.8.1

Thanks, have a nice day.
