### ISSUE TITLE
where to listen to voice ?

### ISSUE THREAD

**Issue by jolatechno** [cropinghigh/sdrpp-tetra-demodulator#22]
Hello, first of all thanks for the great work !

The plugin seems to work on my end, but I can't listen to sound output.

If "Decoder", "Sync" and "CRC" are green, "encryption" is red (so no encryption ?) and "voice" is green (so the signal carries voice data ?), how do I listen to this voice data ?

I don't understand where in sdr++ I can activate sound output from a plugin.

**Comment by cropinghigh** [comment]
Make sure you selected right sink(probably you want Audio) in sinks tab

**Comment by jolatechno** [comment]
Thank you ! I still hear nothing, is that normal (if there is no talking) ?

Does the work "encryption" in red means there is encryption or there is no encryption ? That would explain my problem.

**Comment by jolatechno** [comment]
My bad, it does work. Thank you ! I am just too used to AM and FM where there is background noise when there is no signal.

**Comment by ganguera** [comment]
@jolatechno I'm in the same situation than you. I can't hear anything. How did you solve it? Thanks!

![Image](https://github.com/user-attachments/assets/25ee4a78-1ddb-411b-ad08-5a59cccb45bc)
