### ISSUE TITLE
This works great with tetra-kit

### ISSUE THREAD

**Issue by ericek111** [cropinghigh/sdrpp-tetra-demodulator#4]
I just want to let you know that this works absolutely beautifully and flawlessly with https://gitlab.com/larryth/tetra-kit
Simply do `mkfifo /tmp/tetrabits1` and run the decoder `while true; do ./decoder -i /tmp/tetrabits1 -t 42101; sleep 1; done`. I have it automated with tmux for as many channels as I want. SDR++ will freeze if there's nothing to consume the output from /tmp/tetrabits1 (for testing, you can `cat /tmp/tetrabits1`).

You made me very happy. I've been attempting to do some more CPU-efficient Pi/4 DQPSK demodulation for some time, but I know nothing about DSP. I just randomly found this project with another attempt at googling something I could understand. I've been running it for 3 days now without a hiccup (several hours at a time).

Running this on Ryzen 3900X, CPU usage when decoding 12 TETRA channels in parallel went down from ~1600 % to ~100 % (with 10 MSps). Next I will try to run it on my phone.

Thank you very much.

**Comment by cropinghigh** [comment]
Thank you for your review! It took me around 1 year, with almost no DSP knowledge, to make this demodulator. Currently, CPU usage is not very optimized, there are many unefficient places in the code.
