### ISSUE TITLE
Getting audio from TETRA burst

### ISSUE THREAD

**Issue by alphapats** [cropinghigh/sdrpp-tetra-demodulator#7]
I have been able to implement it successfully. After running `socat - udp-listen:8355 | ./tetra-rx -s -r -e /dev/stdin` command, I am able to view TETRA bursts. Its working good till here. How to get audio from these tetra bursts? I am trying to use telive, but not able to integrate two?

**Comment by cropinghigh** [comment]
Actually this isn't demodulator issue, since BURSTs are being decoded. Check telive and osmo-tetra-sq5bpf manual for details on how to use them

**Comment by cropinghigh** [comment]
should be fixed, since decoder is now included in the module
