### ISSUE TITLE
errors when compile

### ISSUE THREAD

**Issue by SeewhyO6** [cropinghigh/sdrpp-tetra-demodulator#8]
Hello,
I have got error when i compile the last version. With the previous UDP version, that was working well with the tetra-kit 

Debian 12 | SDR++ 1.1.0 (.deb package from nightly build)

`[  2%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/cdec_tet.c.o

[  5%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fbas_tet.c.o
[  7%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fexp_tet.c.o
[ 10%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fmat_tet.c.o
[ 12%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sdec_tet.c.o
[ 15%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_cd.c.o
[ 17%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_dsp.c.o
[ 20%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_sc_d.c.o
[ 22%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/tetra_op.c.o
[ 25%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/hurdle.c.o
[ 27%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/taa1.c.o
[ 30%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea1.c.o
[ 32%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea2.c.o
[ 35%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea3.c.o
[ 37%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c: In function ‘tetra_crypto_db_init’:
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:112:22: warning: implicit declaration of function ‘talloc_zero_array’ [-Wimplicit-function-declaration]
  112 |         tcdb->keys = talloc_zero_array(NULL, struct tetra_key, TCDB_ALLOC_BLOCK_SIZE);
      |                      ^~~~~~~~~~~~~~~~~
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:112:46: error: expected expression before ‘struct’
  112 |         tcdb->keys = talloc_zero_array(NULL, struct tetra_key, TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:113:46: error: expected expression before ‘struct’
  113 |         tcdb->nets = talloc_zero_array(NULL, struct tetra_netinfo, TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c: In function ‘load_keystore’:
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:324:46: warning: implicit declaration of function ‘talloc_realloc’ [-Wimplicit-function-declaration]
  324 |                                 tcdb->nets = talloc_realloc(NULL, tcdb->nets, struct tetra_netinfo, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                              ^~~~~~~~~~~~~~
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:324:79: error: expected expression before ‘struct’
  324 |                                 tcdb->nets = talloc_realloc(NULL, tcdb->nets, struct tetra_netinfo, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                                                               ^~~~~~
/home/yo/sdrpp-tetra-demodulator/src/decoder/src/crypto/tetra_crypto.c:343:79: error: expected expression before ‘struct’
  343 |                                 tcdb->keys = talloc_realloc(NULL, tcdb->keys, struct tetra_key, i + TCDB_ALLOC_BLOCK_SIZE);
      |                                                                               ^~~~~~
make[2]: *** [CMakeFiles/tetra_demodulator.dir/build.make:272 : CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:83 : CMakeFiles/tetra_demodulator.dir/all] Erreur 2
make: *** [Makefile:136 : all] Erreur 2`

**Comment by cropinghigh** [comment]
Looks like it's libosmocore problem. What version you have installed and do you have libosmocore-dev?

**Comment by SeewhyO6** [comment]
> Looks like it's libosmocore problem. What version you have installed and do you have libosmocore-dev?

I have recompile libosmocore and the compilation of sdrpp-tetra-demodulator is fine.
Many thanks for your help.

`[  2%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/cdec_tet.c.o

[  5%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fbas_tet.c.o
[  7%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fexp_tet.c.o
[ 10%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fmat_tet.c.o
[ 12%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sdec_tet.c.o
[ 15%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_cd.c.o
[ 17%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_dsp.c.o
[ 20%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_sc_d.c.o
[ 22%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/tetra_op.c.o
[ 25%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/hurdle.c.o
[ 27%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/taa1.c.o
[ 30%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea1.c.o
[ 32%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea2.c.o
[ 35%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea3.c.o
[ 37%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o
[ 40%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/crc_simple.c.o
[ 42%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tch_reordering.c.o
[ 45%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_conv_enc.c.o
[ 47%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_interleave.c.o
[ 50%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_lower_mac.c.o
[ 52%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_rm3014.c.o
[ 55%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_scramb.c.o
[ 57%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi.c.o
[ 60%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi_cch.c.o
[ 62%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi_tch.c.o
[ 65%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/phy/tetra_burst.c.o
[ 67%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/phy/tetra_burst_sync.c.o
[ 70%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_cmce_pdu.c.o
[ 72%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_common.c.o
[ 75%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_llc.c.o
[ 77%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_llc_pdu.c.o
[ 80%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mac_pdu.c.o
[ 82%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mle.c.o
[ 85%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mle_pdu.c.o
[ 87%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mm_pdu.c.o
[ 90%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_sndcp_pdu.c.o
[ 92%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_tdma.c.o
[ 95%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_upper_mac.c.o
[ 97%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/main.cpp.o
[100%] Linking CXX shared library tetra_demodulator.so
[100%] Built target tetra_demodulator`

**Comment by cropinghigh** [comment]
That's great!
